---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv2
  namespace: postgres-cluster
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/pg-pv2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - made-x407uf
