---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-service
  namespace: postgres-cluster
spec:
  selector:
    app: postgres-cluster
  type: NodePort
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      nodePort: 30001
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cluster
  namespace: postgres-cluster
  labels:
    app: postgres-cluster
spec:
  serviceName: postgres-cluster-service
  replicas: 2
  selector:
    matchLabels:
      app: postgres-cluster
  template:
    metadata:
      labels:
        app: postgres-cluster
    spec:
      containers:
        - name: postgres
          image: postgres:15.3
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-env
                  key: user
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-env
                  key: database
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
        namespace: postgres-cluster
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 1Gi
