---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-service
  namespace: postgres-cluster
spec:
  selector:
    app: postgres-cluster
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30001
      targetPort: 5432
